spring:
  application:
    name: learn-rabbitmq
  rabbitmq:
    addresses: 172.16.2.132:5672
    virtual-host: vhost_accounting_mfm
    requested-heartbeat: 15
    username: accounting
    password: accounting
    cache:
      channel:
        size: 300
      connection:
        mode: CHANNEL
    template:
      retry:
        enabled: true
        initial-interval: 15000
        max-interval: 30000
        max-attempts: 5
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 5
          max-interval: 30000
          initial-interval: 15000
        prefetch: 1
        transaction-size: 1
        concurrency: 1
        max-concurrency: 3
        idle-event-interval: 60000
        default-requeue-rejected: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.16.2.132:8761/eureka,http://172.16.2.133:8761/eureka,http://172.16.2.134:8761/eureka

server:
  port: 9001
  context-path: /learn-rabbitmq
    


  
